### ISSUE TITLE
[Bug] REGEX Not working right within /neuec

### ISSUE THREAD

**Issue by tangerine349** [NotEnoughUpdates/NotEnoughUpdates#193] opened 2022-07-19 19:42 UTC
**Mod Version:** 
2.1-Lunar

**Describe the bug**
When using Regex to flag enchants, its being very random on what it decides to flag

**To Reproduce**
1.  type /neuec
2.  put ((E|G|T).+er)
3. edit the level >0 and the color to whatever youd like

**Expected behavior**
only Titan Killer, Giant Killer and Ender Slayer should flag

**Attachments**
https://gyazo.com/56b06a6b07868cc9d649293d75288f52

**Comment by romangraef** [comment] 2022-09-08 13:17
The problem is that it matches on Exper. You should be able to fix this by ending your regex with a $ (forcing the last character to be at the end). This behaviour might be changed to automatically try to match against the entire enchantment in the future. I will be closing this issue since we don't use githubs issue management anymore.

**Closed by romangraef** 2022-09-08 13:17 UTC
